version: '3.3'

services:
  back:
    container_name: back
    build: ./backend
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    command: bash ./runserver.sh
    volumes:
      - ./media/:/media/
      - ./static/:/static/
      - ./backend/:/app/

  db: 
    container_name: db
    image: postgres:18
    env_file:
      - ./backend/.env
    volumes:
      - ./db-data:/var/lib/postgresql